import { faker } from '@faker-js/faker';

export const mockMessages = [
  {
    id: 1,
    userId: 1,
    userName: faker.person.fullName(),
    message: faker.lorem.sentences({ min: 2, max: 3 }),
    timestamp: faker.date.past({ days: 1 }).toISOString(),
    avatar: faker.image.avatar(),
    isOnline: true,
  },
  {
    id: 2,
    userId: 2,
    userName: faker.person.fullName(),
    message: faker.lorem.sentences({ min: 2, max: 3 }),
    timestamp: faker.date.past({ days: 2 }).toISOString(),
    avatar: faker.image.avatar(),
    isOnline: false,
  },
  {
    id: 3,
    userId: 1,
    userName: faker.person.fullName(),
    message: faker.lorem.sentences({ min: 2, max: 3 }),
    timestamp: faker.date.past({ days: 3 }).toISOString(),
    avatar: faker.image.avatar(),
    isOnline: true,
  },
  {
    id: 4,
    userId: 2,
    userName: faker.person.fullName(),
    message: faker.lorem.sentences({ min: 2, max: 3 }),
    timestamp: faker.date.past({ days: 4 }).toISOString(),
    avatar: faker.image.avatar(),
    isOnline: false,
  },
  {
    id: 5,
    userId: 1,
    userName: faker.person.fullName(),
    message: faker.lorem.sentences({ min: 2, max: 3 }),
    timestamp: faker.date.past({ days: 5 }).toISOString(),
    avatar: faker.image.avatar(),
    isOnline: true,
  },
  {
    id: 6,
    userId: 2,
    userName: faker.person.fullName(),
    message: faker.lorem.sentences({ min: 2, max: 3 }),
    timestamp: faker.date.past({ days: 6 }).toISOString(),
    avatar: faker.image.avatar(),
    isOnline: false,
  },
  {
    id: 7,
    userId: 1,
    userName: faker.person.fullName(),
    message: faker.lorem.sentences({ min: 2, max: 3 }),
    timestamp: faker.date.past({ days: 7 }).toISOString(),
    avatar: faker.image.avatar(),
    isOnline: true,
  },
  {
    id: 8,
    userId: 2,
    userName: faker.person.fullName(),
    message: faker.lorem.sentences({ min: 2, max: 3 }),
    timestamp: faker.date.past({ days: 8 }).toISOString(),
    avatar: faker.image.avatar(),
    isOnline: false,
  },
  {
    id: 9,
    userId: 1,
    userName: faker.person.fullName(),
    message: faker.lorem.sentences({ min: 2, max: 3 }),
    timestamp: faker.date.past({ days: 9 }).toISOString(),
    avatar: faker.image.avatar(),
    isOnline: true,
  },
  {
    id: 10,
    userId: 2,
    userName: faker.person.fullName(),
    message: faker.lorem.sentences({ min: 2, max: 3 }),
    timestamp: faker.date.past({ days: 10 }).toISOString(),
    avatar: faker.image.avatar(),
    isOnline: false,
  }
];